sudo: false
language: python
env:
  global:
    - SHUUP_BROWSER_TESTS=1
    - SHUUP_TESTS_CI=1
    - SHUUP_WORKBENCH_DISABLE_MIGRATIONS=1
cache:
  bundler: true
  directories:
    - "$HOME/.cache/pip"
    - "$HOME/.npm"
    - "$HOME/.cache/shuup/admin"
    - "$HOME/.cache/shuup/front"
    - "$HOME/.cache/shuup/gdpr"
    - "$HOME/.cache/shuup/regions"
    - "$HOME/.cache/shuup/notify"
    - "$HOME/.cache/shuup/classic_gray"
    - "$HOME/.cache/shuup/xtheme"
    - shuup/admin/node_modules
    - shuup/front/node_modules
    - shuup/gdpr/node_modules
    - shuup/notify/node_modules
    - shuup/regions/node_modules
    - shuup/themes/classic_gray/node_modules
    - shuup/xtheme/node_modules
jobs:
  include:
    - stage: development
      python: 3.6
      addons:
        firefox: "latest"
      services:
        - xvfb
      before_install:
        - sudo apt-get -y install gettext
        - wget https://github.com/mozilla/geckodriver/releases/download/v0.29.1/geckodriver-v0.29.1-linux64.tar.gz
        - mkdir geckodriver
        - tar -xzf geckodriver*.tar.gz -C geckodriver
        - export PATH=$PATH:$PWD/geckodriver
        - "nvm install 10"
        - "nvm use 10"
        - "export DISPLAY=:99.0"
        - "npm install -g selenium-standalone@6.15.3"
        - "selenium-standalone install"
        - "selenium-standalone start &"
        - pip install -r requirements-tests.txt
        - python setup.py build_resources --ci
        - python setup.py build_messages
      script:
        - py.test -v --nomigrations shuup_tests/browser/admin/
        - py.test -v --nomigrations shuup_tests/browser/front/
