version: "3.7"

services:
  shuup:
    container_name: shuup
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/.sqlite
    tty: true
    restart: unless-stopped
