name: "PYPI"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version of the release, e.g. 1.0.0"
        required: true

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2
        with:
          ref: 'v${{ github.event.inputs.version }}'

      - name: "Set up Python"
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'

      - name: "Set up Node"
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: "Install build dependencies"
        run: |
          sudo apt-get install --no-install-recommends --assume-yes gettext
          pip install --upgrade --disable-pip-version-check pip
          pip install --upgrade setuptools wheel
          pip install --upgrade shuup

      - name: "Build the wheel"
        run: |
          rm -rf build/
          rm -rf dist/
          python setup.py bdist_wheel

      - name: "Upload the wheel to PYPI"
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
